First pass of new submission docs
brain-score/brain-score pull request #396
Opened 2023-11-06 18:15 UTC by mike-ferguson

This PR moved the developer.md file into a new home, submission.rst. This is the first pass (content-wise) after being updated for the new release. @kvfairchild @mschrimpf please review if I missed anything or if you want to add anything else!

2023-11-07 07:40 UTC, mschrimpf requested changes

2023-11-07 07:40 UTC, mschrimpf commented on docs/source/modules/submission.rst
> +ecosystem, with each part explained below:
```suggestion
To provide an automatic scoring mechanism for artificial models of the brain, 
Brain-Score provides an automated submission system.
This enables us to automatically score new models on existing benchmarks,
as well as new benchmarks against existing models.
```

2023-11-07 07:40 UTC, mschrimpf commented on docs/source/modules/submission.rst
> +    :alt: alternate text
```suggestion
    :alt: submission system diagram
```

2023-11-07 07:40 UTC, mschrimpf commented on docs/source/modules/submission.rst
> +    `Github <https://github.com/brain-score/brain-score.web>`_, handles our front end. It is implemented using Django
```suggestion
    The `website <www.brain-score.org>`_ (`Github <https://github.com/brain-score/brain-score.web>`_) handles our front end. It is implemented using Django
```

2023-11-07 07:40 UTC, mschrimpf commented on docs/source/modules/submission.rst
> +    see their profile, personal (private) leaderboard as well as the public leaderboard.
```suggestion
    and also accesses the database instance. 
    
    Users can submit plugins as a zip file via the website or as a pull request via Github. 
    Zip file submissions are converted into a pull request that is automatically merged if tests pass.
    Once a pull request has been merged and if there are new model or benchmark plugins, 
    a Github action triggers the scoring runs which are handled by Jenkins 
    and run on the OpenMind compute cluster.
```

2023-11-07 07:40 UTC, mschrimpf commented on docs/source/modules/submission.rst
> +-  **Openmind**
```suggestion
-  **OpenMind**
```

2023-11-07 07:40 UTC, mschrimpf commented on docs/source/modules/submission.rst
> +    contains a script for model submission (`score_model.sh`) and for unittests (`unittests_brainscore.sh`). The scripts
@kvfairchild are these two scripts still accurate?

2023-11-07 07:40 UTC, mschrimpf commented on docs/source/modules/submission.rst
> +    From there, Jenkins reports the results back to its caller (the website) and emails the user.
```suggestion
    and shutting everything down again. 
    For scoring runs, results are stored in the database and sent to the user via email.
    For unit tests, results are reported back to Github.
```

2023-11-07 07:40 UTC, mschrimpf commented on docs/source/modules/submission.rst
> +<https://github.com/brain-score/brain-score/blob/master/brainscore/submission/db_schema.uml>`_:
move this file into `docs/source/modules`

2023-11-07 07:40 UTC, mschrimpf commented on docs/source/modules/submission.rst
> +project, along with django commands, to adjust the tables (in `benchmarl/models.py`). Once changes are made locally,
```suggestion
project, along with django commands, to adjust the tables (in `benchmark/models.py`). The schema also has to be updated in `core <https://github.com/brain-score/core/blob/main/brainscore_core/submission/database_models.py>`_. Once changes are made locally,
```

2023-11-07 07:40 UTC, mschrimpf commented on docs/source/modules/submission.rst
> +In addition to the main job for scoring submission (run_benchmarks), Jenkins contains a second job (dev_run_benchmarks),
```suggestion
In addition to the main job for scoring submission (`score_plugins`), Jenkins contains a second job (`dev_score_plugins`),
```
@kvfairchild correct?

2023-11-07 07:40 UTC, mschrimpf commented on docs/source/modules/submission.rst
> +aptly named dev_score_models.sh. That script is what is run on Jenkins's dev environment. Once the development job runs
@kvfairchild still the correct script names?

2023-11-07 07:40 UTC, mschrimpf commented on docs/source/modules/submission.rst
> +two types of submissions possible:
@kvfairchild not sure this is still the best way to describe

2023-12-19 01:30 UTC, kvfairchild commented on docs/source/modules/submission.rst
> +    and also accesses the database instance. When user submit their models in form of a zip file, the website triggers
```suggestion
    and also accesses the database instance. When a user submits their models in form of a zip file, the website triggers
```

2024-01-02 09:07 UTC, merged