remove lab identifiers from plugin identifiers
brain-score/brain-score pull request #402
Opened 2023-11-15 07:26 UTC by mschrimpf

Change identifiers from `<lab-pi-lastname>.<firstauthor-lastname><year>` to `<firstauthor-lastname><year>`

Note that this leads to some discrepancy:
* the S3 files still have the lab identifier prefix
* this also means that while e.g. stimulus sets will be loaded with just the `<firstauthor-lastname><year>` identifier, the `stimulus_set.identifier` will still include the lab prefix

2023-12-18 14:52 UTC, mschrimpf commented
verified that no more labs show up in library plugin identifiers with the following script (modified from [`parse_plugin_changes.py`](https://github.com/brain-score/core/blob/main/brainscore_core/plugin_management/parse_plugin_changes.py)):
```python
def get_plugin_ids(plugin_type: str) -> List[str]:
    plugin_type_root = Path(__file__).parent.parent / 'brainscore_vision' / plugin_type
    plugin_ids = []

    for plugin_dirname in plugin_type_root.iterdir():
        if not plugin_dirname.is_dir() or str(plugin_dirname).endswith('__pycache__'): continue

        init_file = plugin_dirname / '__init__.py'
        with open(init_file) as f:
            registry_name = plugin_type.strip(
                's') + '_registry'  # remove plural and determine variable name, e.g. "models" -> "model_registry"
            plugin_registrations = [line for line in f if f"{registry_name}["
                                    in line.replace('\"', '\'')]
            for line in plugin_registrations:
                result = re.search(f'{registry_name}\[.*\]', line)
                identifier = result.group(0)[len(registry_name) + 2:-2]  # remove brackets and quotes
                plugin_ids.append(identifier)

    return plugin_ids


def __main__():
    for plugin_type in ['data', 'metrics', 'benchmarks', 'models']:
        plugin_ids = get_plugin_ids(plugin_type)
        ids_with_dot = [plugin_id for plugin_id in plugin_ids if '.' in plugin_id]
        print(ids_with_dot)

```

2023-12-19 05:32 UTC, kvfairchild requested changes
[Travis tests](https://app.travis-ci.com/github/brain-score/brain-score/builds/267918408) need resolving; they are (correctly) marked as failing on the PR public build but also need review in the (incorrectly marked as passing) private build. I've opened a ticket with Travis support about the incorrect pass (see Slack for further details).

I don't think any of the [Jenkins failures](http://braintree.mit.edu:8080/job/unittest_brainscore/1226/) are actually stemming from  this PR but it would be nice to track those down so we can merge this with a green Jenkins check as well.

2023-12-19 07:04 UTC, mschrimpf commented on brainscore_vision/benchmarks/objectnet/__init__.py
> +benchmark_registry['BarbuMayo2019-top1'] = Objectnet
you're right, will update

2023-12-19 07:09 UTC, mschrimpf commented on brainscore_vision/data/imagenetslim15000/test.py
> +    assert load_dataset('ImageNetSlim15000') is not None
[right here](https://github.com/brain-score/brain-score/blob/43a51acc41093c5a790fdbc1b75c6694afeeecaa/brainscore_vision/data/imagenetslim15000/__init__.py#L5)

2023-12-19 07:10 UTC, mschrimpf commented on brainscore_vision/data/imagenetslim15000/test.py
> +    assert load_dataset('ImageNetSlim15000') is not None
but it should be `load_stimulus_set`

2024-01-03 07:33 UTC, merged